### PR TITLE
Add possibility to filter by genre

### PR DESCRIPTION
**Pull request by martini97**
Adds the possibility to filter movies by genre

### CODE REVIEW

**Comment by fernahh** [comment]
@martini97 can you add a gif ou screenshot to pull request description?

**Comment by martini97** [comment]
@fernahh sure, can I send a ttyrecord file?

**Comment by fernahh** [comment]
@martini97 yep

**Comment by martini97** [comment]
ttyrecord had to rename it to .gif to upload

**Comment by fernahh** [comment]
@martini97 can you try using [Peek](https://github.com/phw/peek) or [Kap](https://getkap.co/)?

**Pull request closed without merging**
